//filters
const CHANGE_REGION = 'CHANGE_REGION';
const CHANGE_CITY = 'CHANGE_CITY';
const CHANGE_PRICE_FROM = 'CHANGE_PRICE_FROM';
const CHANGE_PRICE_TO = 'CHANGE_PRICE_TO';
const CHANGE_STATE_PRODUCT = 'CHANGE_STATE_PRODUCT';
const CHANGE_SELLER = 'CHANGE_SELLER';
const CHANGE_IS_WITH_PHOTO = 'CHANGE_IS_WITH_PHOTO';
const CHANGE_FASHIONABLE_SUMMER = 'CHANGE_FASHIONABLE_SUMMER';
const CHANGE_INSTALLMENT_HALVA = 'CHANGE_INSTALLMENT_HALVA';
const CHANGE_IS_EXCHANGE = 'CHANGE_IS_EXCHANGE';
//products
const CHANGE_CORRECT_PRODUCTS = 'CHANGE_CORRECT_PRODUCTS';
const CHANGE_PRODUCTS = 'CHANGE_PRODUCTS';
const CHANGE_CATEGORIES_FILTER = 'CHANGE_CATEGORIES_FILTER';
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const GET_PRODUCTS_ASYNC = 'GET_PRODUCTS_ASYNC';
//user
const TOGGLE_TAB = 'TOGGLE_TAB';
const REGISTRATION_USER = 'REGISTRATION_USER';
const REGISTRATION_USER_ASYNC = 'REGISTRATION_USER_ASYNC';
const LOGIN_USER = 'LOGIN_USER';
const LOGIN_USER_ASYNC = 'LOGIN_USER_ASYNC';
const OPEN_AUTHORIZATION = 'OPEN_AUTHORIZATION';
const LOGOUT_USER = 'LOGOUT_USER';

export{
  CHANGE_IS_EXCHANGE,
  CHANGE_INSTALLMENT_HALVA,
  CHANGE_FASHIONABLE_SUMMER,
  CHANGE_SELLER,
  CHANGE_STATE_PRODUCT,
  CHANGE_PRICE_FROM,
  CHANGE_CITY,
  CHANGE_CATEGORIES_FILTER,
  CHANGE_CORRECT_PRODUCTS,
  CHANGE_IS_WITH_PHOTO,
  CHANGE_PRICE_TO,
  CHANGE_PRODUCTS,
  CHANGE_REGION,
  ADD_PRODUCTS,
  GET_PRODUCTS_ASYNC,
  TOGGLE_TAB,
  LOGIN_USER,
  LOGIN_USER_ASYNC,
  REGISTRATION_USER,
  REGISTRATION_USER_ASYNC,
  OPEN_AUTHORIZATION,
  LOGOUT_USER
}
