// products
const CHANGE_PRODUCTS = 'CHANGE_PRODUCTS';
const CHANGE_CATEGORY_FILTER = 'CHANGE_CATEGORY_FILTER';
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const GET_PRODUCTS_ASYNC = 'GET_PRODUCTS_ASYNC';
const CREATE_PRODUCT_ASYNC = 'CREATE_PRODUCT_ASYNC';
// user
const TOGGLE_TAB = 'TOGGLE_TAB';
const REGISTRATION_USER = 'REGISTRATION_USER';
const REGISTRATION_USER_ASYNC = 'REGISTRATION_USER_ASYNC';
const LOGIN_USER_ASYNC = 'LOGIN_USER_ASYNC';
const OPEN_MODEL = 'OPEN_MODEL';
const CHANGE_USER = 'CHANGE_USER';
const TOGGLE_IS_REGISTRATION = 'TOGGLE_IS_REGISTRATION';
const GET_USER_PRODUCTS = 'GET_USER_PRODUCTS';

export {
  CHANGE_CATEGORY_FILTER,
  CHANGE_PRODUCTS,
  ADD_PRODUCTS,
  GET_PRODUCTS_ASYNC,
  CREATE_PRODUCT_ASYNC,
  TOGGLE_TAB,
  LOGIN_USER_ASYNC,
  REGISTRATION_USER,
  REGISTRATION_USER_ASYNC,
  OPEN_MODEL,
  CHANGE_USER,
  TOGGLE_IS_REGISTRATION,
  GET_USER_PRODUCTS
};
