const CHANGE_REGION = 'CHANGE_REGION';
const CHANGE_CITY = 'CHANGE_CITY';
const CHANGE_PRICE_FROM = 'CHANGE_PRICE_FROM';
const CHANGE_PRICE_TO = 'CHANGE_PRICE_TO';
const CHANGE_STATE_PRODUCT = 'CHANGE_STATE_PRODUCT';
const CHANGE_SELLER = 'CHANGE_SELLER';
const CHANGE_IS_WITH_PHOTO = 'CHANGE_IS_WITH_PHOTO';
const CHANGE_FASHIONABLE_SUMMER = 'CHANGE_FASHIONABLE_SUMMER';
const CHANGE_INSTALLMENT_HALVA = 'CHANGE_INSTALLMENT_HALVA';
const CHANGE_IS_EXCHANGE = 'CHANGE_IS_EXCHANGE';
const CHANGE_CORRECT_PRODUCTS = 'CHANGE_CORRECT_PRODUCTS';
const CHANGE_PRODUCTS = 'CHANGE_PRODUCTS';
const CHANGE_CATEGORIES_FILTER = 'CHANGE_CATEGORIES_FILTER';
const ADD_PRODUCTS = 'ADD_PRODUCTS';
const GET_PRODUCTS_ASYNC = 'GET_PRODUCTS_ASYNC';

export{
  CHANGE_IS_EXCHANGE,
  CHANGE_INSTALLMENT_HALVA,
  CHANGE_FASHIONABLE_SUMMER,
  CHANGE_SELLER,
  CHANGE_STATE_PRODUCT,
  CHANGE_PRICE_FROM,
  CHANGE_CITY,
  CHANGE_CATEGORIES_FILTER,
  CHANGE_CORRECT_PRODUCTS,
  CHANGE_IS_WITH_PHOTO,
  CHANGE_PRICE_TO,
  CHANGE_PRODUCTS,
  CHANGE_REGION,
  ADD_PRODUCTS,
  GET_PRODUCTS_ASYNC
}
